### ISSUE TITLE
Opening Wii U BFRES causes an error

### ISSUE THREAD

**Issue by slashiee** [KillzXGaming/Switch-Toolbox#16]
I've tried Callie and Marie's Wii U BFRES models and both result in the same error.

![2018-12-01_23-35-24](https://user-images.githubusercontent.com/15317421/49337068-43843b00-f5c2-11e8-84f4-2b947dfa0161.png)
```
************** Exception Text **************
System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at FirstPlugin.GTX.Decode(GX2Surface tex) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\Texture\GTX.cs:line 490
   at FirstPlugin.FTEX.Read(Texture tex) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\Texture\FTEX.cs:line 192
   at Bfres.Structs.ResourceFile.AddFTEXTextures(ResFile resFile) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\BFRES\Bfres Structs\ResourceFile.cs:line 281
   at Bfres.Structs.ResourceFile.Load(ResFile res) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\BFRES\Bfres Structs\ResourceFile.cs:line 127
   at FirstPlugin.BFRESRender.LoadFile(ResFile resFileU) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\GL\BFRES_Render.cs:line 53
   at FirstPlugin.BFRES.Load() in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\BFRES.cs:line 120
   at FirstPlugin.SARC.OpenFile(String FileName, Byte[] data, SarcEntry sarcEntry, Boolean Compressed, CompressionType CompType) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\SARC.cs:line 406
   at FirstPlugin.SARC.SarcEntry.OnDoubleMouseClick(TreeView treeView) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox - Copy\Switch_FileFormatsMain\FileFormats\SARC.cs:line 256
   at Switch_Toolbox.Library.ObjectList.treeView1_MouseDoubleClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
[Npc_Idol.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/2636735/Npc_Idol.zip)

**Comment by vgisuruex** [comment]
it's because the texture could not be loaded. in the beta releases page it says that "Note Wii U has textures disabled for now until next version as it would corrupt things". so wait until the next update

**Comment by slashiee** [comment]
It's working now, thank you
![2018-12-03_17-08-47](https://user-images.githubusercontent.com/15317421/49411534-1ba9ea00-f71e-11e8-87ac-6a06fa15c4d6.png)
