### ISSUE TITLE
"Debug" BCMDL error

### ISSUE THREAD

**Issue by NWPlayer123** [KillzXGaming/Switch-Toolbox#170]
I'm sure this isn't high on the list of priorities but these couple debug files in Rhythm Thief 3DS throw -> (tested on latest commit as of this issue)
```
BcresLibrary.BcresException: Could not find data section!
   at BcresLibrary.BcresFile.get_Data()
   at FirstPlugin.BCRES.Load(Stream stream) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BCRES\BCRES.cs:line 63
   at Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.ExplorerFile.OpenFile()
```
[dbg_akiyama.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4004445/dbg_akiyama.zip)

**Comment by KillzXGaming** [comment]
It appears to use a much older version (v4) than what most use (v5 or higher) so the structure has some differences.
