### ISSUE TITLE
Unable to export Wii U BFRES' scene animations (.bfscn)

### ISSUE THREAD

**Issue by Wheatley606** [KillzXGaming/Switch-Toolbox#215]
Whenever I try to export a scene animation of a Wii U BFRES, I get an error stating that "Object reference not set to an instance of an object."
The Switch counterpart of the scene animation works fine when I want to export it

Here's the error if you're inter rested.
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bfres.Structs.FSCN.Export(String FileName) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\Bfres Structs\SubFiles\FSCN.cs:line 92
   at Toolbox.Library.NodeWrappers.STGenericWrapper.ExportAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by KillzXGaming** [comment]
Should be fixed from https://github.com/KillzXGaming/Switch-Toolbox/commit/cb86773b9c54c2815d2473b06232e5cb8dba8659
