### ISSUE TITLE
Unhandled Exception when Opening Wii U BARS

### ISSUE THREAD

**Issue by notmuhHoriz** [KillzXGaming/Switch-Toolbox#22]
Opening any Wii U BOTW BARS file brings up an error. Are Wii U BARS supported yet?

> ************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at Syroot.BinaryData.BinaryDataReader.ReadUInt32()
   at Syroot.BinaryData.BinaryDataReader.ReadMultiple[T](Int32 count, Func`1 readFunc)
   at Syroot.BinaryData.BinaryDataReader.ReadUInt32s(Int32 count)
   at BarsLib.BARS.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.BARS..ctor(Stream stream)
   at FirstPlugin.BARS.Load() in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox-38ceb8d7163902ecb569774ab4db327a194d6f99\Switch_FileFormatsMain\FileFormats\BARS.cs:line 169
   at Switch_Toolbox.MainForm.OpenFile(String FileName, Byte[] data, Boolean Compressed, CompressionType CompType) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox-38ceb8d7163902ecb569774ab4db327a194d6f99\Switch_Toolbox\MainForm.cs:line 349
   at Switch_Toolbox.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\Nathan\Documents\GitHub\Switch_Toolbox\Switch-Toolbox-38ceb8d7163902ecb569774ab4db327a194d6f99\Switch_Toolbox\MainForm.cs:line 447
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by KillzXGaming** [comment]
Wii U BARS is (just a sarc) however BOTW uses switch's format in big endian. Currently only little endian is supported but i'll look into it and test it in the next update.

**Comment by KillzXGaming** [comment]
Alright latest should work with BOTW Wii U BARS now.
