### ISSUE TITLE
Unable to import specific model

### ISSUE THREAD

**Issue by swampatha** [KillzXGaming/Switch-Toolbox#258]
All day I have been working on redoing my MKT ports to MK8D, and they've all had no issues except for one. I have redone it three times over and everytime I try to import this one specific model, STB always errors out for me.
### Model
[Test1.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/4921461/Test1.zip)

### Error
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Bfres.Structs.FSHP.GetIndices(FSKL fskl) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\Bfres Structs\SubFiles\FMDL\FSHP.cs:line 1340
   at Bfres.Structs.FMDL.AddOjects(String FileName, ResFile resFileNX, ResFile resFileU, Boolean Replace) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\Bfres Structs\SubFiles\FMDL.cs:line 1211
   at Bfres.Structs.FMDL.Replace(String FileName) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\Bfres Structs\SubFiles\FMDL.cs:line 599
   at Toolbox.Library.NodeWrappers.STGenericWrapper.ReplaceAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/OpenTK.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Octokit.DLL
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Syroot.BinaryData.dll
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Plugins/SPICA.DLL
----------------------------------------
KCLExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Plugins/KCLExt.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Newtonsoft.Json.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
SARCExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/SARCExt.dll
----------------------------------------
DirectXTexNet
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/DirectXTexNet.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
OptaneShellExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Intel/OptaneShellExtensions/OptaneShellExt.dll
----------------------------------------
SharpShell
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Program%20Files/Intel/OptaneShellExtensions/SharpShell.DLL
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Program%20Files/Intel/OptaneShellExtensions/log4net.DLL
----------------------------------------
PinningServiceApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Intel/OptaneShellExtensions/PinningServiceApi.DLL
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AssimpNet
    Assembly Version: 4.1.0.0
    Win32 Version: 4.1.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/AssimpNet.DLL
----------------------------------------
Cyotek.Windows.Forms.ImageBox
    Assembly Version: 1.2.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/Cyotek.Windows.Forms.ImageBox.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.76
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Users/nrams/Downloads/Toolbox-Latest/Lib/ObjectListView.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KillzXGaming** [comment]
This likely due to how the bones are named. They have too much extra strings to the end of it like _$AssimpFbx$_Translation so they wouldn't map to the original boneset.
