### ISSUE TITLE
Unable to export Skeleton

### ISSUE THREAD

**Issue by ShrineFox** [KillzXGaming/Switch-Toolbox#38]
This occurs for me so far with new/edited models.
Right clicking the Skeleton of a Model and choosing "Export Skeleton" results in the following error:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Bfres.Structs.FSKL.fsklNode.Export(String FileName) in C:\Users\Nathan\Documents\GitHub\SwitchToolboxV1\Switch_FileFormatsMain\FileFormats\BFRES\Bfres Structs\SubFiles\FMDL\FSKL.cs:line 120
   at Switch_Toolbox.Library.NodeWrappers.STGenericWrapper.ExportAction(Object sender, EventArgs e) in C:\Users\Nathan\Documents\GitHub\SwitchToolboxV1\Switch_Toolbox_Library\Generics\STGenericWrapper.cs:line 206
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by KillzXGaming** [comment]
Fixed in https://github.com/KillzXGaming/Switch-Toolbox/commit/211326d25386ff7005aa640c687284526ad2a85d
