### ISSUE TITLE
Error trying to save Metroid Dread bctex

### ISSUE THREAD

**Issue by BruhLookAtThis** [KillzXGaming/Switch-Toolbox#404]
Using the latest build of Toolbox from Releases, every time I try to save an .bctex (from Metroid Dread) (it only lets me save as an .xtx file), I get this error

************** Exception Text **************
System.NotImplementedException: Make sure to impliment a IFileInfo instance if a format is being created!
   at Toolbox.Library.IO.STFileSaver.SaveFileFormat(IFileFormat FileFormat, String FileName, Boolean EnableDialog, String DetailsLog)
   at FirstPlugin.XTX.Save(Object sender, EventArgs args) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Texture\XTX.cs:line 90
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

How do I fix this? Says I need to "Make sure to impliment a lFileInfo instance if a format is being created!". No clue what that means

**Comment by shibbo** [comment]
means that the operation it's trying to do is not support yet.

**Comment by BruhLookAtThis** [comment]
> means that the operation it's trying to do is not supported yet. If this is not intentional, then it's a bug. But something tells me that it just doesn't support saving this format yet.

![Untitled](https://user-images.githubusercontent.com/58442192/136827574-bcaff9a0-319d-4522-8324-ca3f8c844bb2.png)
Not understanding why tho, Killz & another person have successfully saved bctex files

**Comment by KillzXGaming** [comment]
Seems the right click menu is just screwed up due to xtx being attached to the tree node so it attempts to save xtx by itself. Just do File - Save for now which should work fine.

**Comment by BruhLookAtThis** [comment]
Nice, that worked. Thanks!
