### ISSUE TITLE
Issues with BNTX with more than one array level

### ISSUE THREAD

**Issue by masagrator** [KillzXGaming/Switch-Toolbox#43]
It looks like this tool has some issues if BNTX contains more than one layer. 
It can't export properly to DDS (exported file shows nothing, importing it crashes app)

Importing different file than bftex for one layer changes structure of file.
F.e. before importing
![image](https://user-images.githubusercontent.com/8557858/55380680-369c3780-5521-11e9-8691-20c57bb76669.png)

After Replace with png, the same format, Image Dimension Dim2D or Dim2DArray (doesn't matter)
![image](https://user-images.githubusercontent.com/8557858/55380869-dce83d00-5521-11e9-8e88-aa17c94c353b.png)

And it deletes other array levels except this imported one and can't export anything more than first array layer with PNG. 

I'm working with fonts from Zelda Breath of the Wild.

**Comment by KillzXGaming** [comment]
Only 2D surfaces work but i'll be adding in multiple types soon. For now on the latest build you can "Image -Edit in external program" (Or click on the blue image icon next to the save one) which will open the image in whatever program opens DDS (ideally something that supports BC4) and edit in that. It'll save back when you save the file. I

**Comment by KillzXGaming** [comment]
Another update with this. DDS now supports array textures (export and import). A custom UI to add array textures and replacing specific arrays/mip maps with png,jpg,tiff, etc is planned atm.

**Comment by SilentStorm-1986** [comment]
I can't find any way to import texture arrays. I tried creating a DDS texture array with Gimp 2.10.30 and matched all the parameters to the original file. Only the first file gets imported and the rest of the array is erased.

When replacing a file in the array manually (Edit in External Program) I receive the error
"Failed to Compress and Swizzle the Image"
System.Exception: Unsupported Depth **(depth of the array)**!
   at Toolbox.Library.GX2.CreateGx2Texture(Byte[] imageData, String Name, UInt32 TileMode, UInt32 AAMode, UInt32 Width, UInt32 Height, UInt32 Depth, UInt32 Format, UInt32 swizzle, UInt32 SurfaceDim, UInt32 MipCount)
   at Bfres.Structs.FTEX.SetImageData(Bitmap bitmap, Int32 ArrayLevel) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\BFRES\Bfres Structs\SubFiles\FTEX.cs:line 492

Hats off to you for your hard work!

**Comment by DragarX** [comment]
Any more updates on image arrays? Pokemon scarlet and violet use arrays for their terrain textures and currently you can edit the textures and replace them, when you export it currently corrupts all the textures aside from the first.
It also crashes when you try to resize any images in an array

**Comment by SilentStorm-1986** [comment]
Replacing the texture will result in errors in every array element after the first. It's currently possible to delete the texture and import an edited DDS array. However this will result in mip mapping errors in game.

After going through the code & assemblies, I'm pretty sure that the issue comes down to the mip offsets. My theory is that the mip offsets are supposed to point to the offsets within the BFRES or BNTX file, _not_ the offsets within the individual textures.

Here's some of the debugging output when an original file is read (Terrain):
`UserDataDict offset: 448
UserDataDict offset: 15512
UserDataDict Count: 7
UserData offset: 14680
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
73728
204800
237568
245760
247808
248320
248832
249344
249856
250368
UserDataDict offset: 17232
UserDataDict Count: 7
UserData offset: 16400
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
1515520
1777664
1843200
1859584
1863680
1864704
1865216
1865728
1866240
1866752
UserDataDict offset: 18616
UserDataDict Count: 7
UserData offset: 18112
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4333568
4366336
4374528
4376576
4377600
4378112
4378624
4379136
4379648
UserDataDict offset: 20032
UserDataDict Count: 7
UserData offset: 19488
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4380672
4382720
4383744
4384256
4384768
4385280
4385792
4386304
UserDataDict offset: 21920
UserDataDict Count: 7
UserData offset: 20896
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4392960
4397056
4398080
4398592
4399104
4399616
4400128
UserDataDict offset: 23680
UserDataDict Count: 7
UserData offset: 22792
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4491264
4495360
4496384
4496896
4497408
4497920
4498432
4498944
UserDataDict offset: 25560
UserDataDict Count: 7
UserData offset: 24536
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4564992
4566016
4566528
4567040
4567552
4568064
UserDataDict offset: 27728
UserDataDict Count: 7
UserData offset: 26416
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4608000
4609024
4609536
4610048
4610560
4611072
UserDataDict offset: 29344
UserDataDict Count: 7
UserData offset: 28608
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4672512
4705280
4713472
4715520
4716032
4716544
4717056
4717568
4718080
UserDataDict offset: 30904
UserDataDict Count: 7
UserData offset: 30208
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
4967424
4971520
4972544
4973056
4973568
4974080
4974592
UserDataDict offset: 32504
UserDataDict Count: 7
UserData offset: 31768
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
5008384
5012480
5013504
5014016
5014528
5015040
5015552
UserDataDict offset: 33888
UserDataDict Count: 7
UserData offset: 33384
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
5057536
5090304
5098496
5100544
5101056
5101568
5102080
5102592
5103104
UserDataDict offset: 35312
UserDataDict Count: 7
UserData offset: 34768
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
5106688
5139456
5147648
5149696
5150720
5151232
5151744
5152256
5152768
UserDataDict offset: 40880
UserDataDict Count: 7
UserData offset: 36208
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
5200896
5725184
5856256
5889024
5897216
5899264
5899776
5900288
5900800
5901312
5901824
UserDataDict offset: 46440
UserDataDict Count: 7
UserData offset: 41768
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
63675392
63806464
63839232
63847424
63849472
63849984
63850496
63851008
63851520
63852032
UserDataDict offset: 52560
UserDataDict Count: 7
UserData offset: 47312
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
78633984
78650368
78654464
78655488
78656000
78656512
78657024
78657536
UserDataDict offset: 58680
UserDataDict Count: 7
UserData offset: 53432
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
81091584
81099776
81101824
81102336
81102848
81103360
81103872
81104384
UserDataDict offset: 0
UserDataDict Count: 0
UserData offset: 0
UserData count: 0
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
82525184
82525696
82526208
82526720
82527232
82527744
UserDataDict offset: 63080
UserDataDict Count: 7
UserData offset: 60272
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
82528256
82536448
82538496
82539008
82539520
82540032
82540544
82541056
UserDataDict offset: 66760
UserDataDict Count: 7
UserData offset: 63952
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
83230720
83234816
83235840
83236352
83236864
83237376
83237888
83238400
UserDataDict offset: 68408
UserDataDict Count: 7
UserData offset: 67576
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
83632128
UserDataDict offset: 69824
UserDataDict Count: 7
UserData offset: 69280
UserData count: 7
Texture Layout: 1
Sparse binding: 0
Sparse residency: 0
83636224
83638272
83639296
83639808
83640320
83640832
83641344
83641856`

The number lists are the offsets from the original file. Notice how they are incremental from the last set of offsets.

Here is some of the debugging output from _writing_ the file.
`SelectedSection TreeNode: Terrain.Tex
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 4
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 3
Mip count: 10
Sample Count: 1
Surface format: BC4_UNORM
Access flags: Texture
Width: 512
Height: 512
Depth: 1
Array count: 8
Texture layout: 4
Texture layout2: 65543
Total size: 1441792
Alignment: 512
Channels: 33686018
Surface dim: Dim2DArray
Name: WaterEmm
UserDataDict offset: 14080
UserDataDict count: 7
UserData offset: 14048
UserData count: 7
0
131072
163840
172032
174080
174592
175104
175616
176128
176640
SaveUserData: 14680, 7
SaveUserDataData: 15128, 40
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 4
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 10
Sample Count: 1
Surface format: BC5_UNORM
Access flags: Texture
Width: 512
Height: 512
Depth: 1
Array count: 8
Texture layout: 4
Texture layout2: 65543
Total size: 2818048
Alignment: 512
Channels: 16843522
Surface dim: Dim2DArray
Name: WaterNrm
UserDataDict offset: 15800
UserDataDict count: 7
UserData offset: 15768
UserData count: 7
0
262144
327680
344064
348160
349184
349696
350208
350720
351232
SaveUserData: 16400, 7
SaveUserDataData: 16848, 40
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 1
Mip count: 9
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 256
Height: 128
Depth: 1
Array count: 1
Texture layout: 2
Texture layout2: 65543
Total size: 47104
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerCrossAlb
UserDataDict offset: 17520
UserDataDict count: 7
UserData offset: 17488
UserData count: 7
0
32768
40960
43008
44032
44544
45056
45568
46080
SaveUserData: 18112, 7
SaveUserDataData: 18560, 5
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC1_SRGB
Access flags: Texture
Width: 32
Height: 128
Depth: 1
Array count: 2
Texture layout: 2
Texture layout2: 65543
Total size: 12288
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: GrassAlb
UserDataDict offset: 18904
UserDataDict count: 7
UserData offset: 18872
UserData count: 7
0
2048
3072
3584
4096
4608
5120
5632
SaveUserData: 19488, 7
SaveUserDataData: 19936, 10
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 1
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 7
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 64
Height: 64
Depth: 1
Array count: 12
Texture layout: 1
Texture layout2: 65543
Total size: 98304
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerFallenLeavesAlb
UserDataDict offset: 20320
UserDataDict count: 7
UserData offset: 20288
UserData count: 7
0
4096
5120
5632
6144
6656
7168
SaveUserData: 20896, 7
SaveUserDataData: 21344, 60
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 32
Height: 128
Depth: 1
Array count: 9
Texture layout: 2
Texture layout2: 65543
Total size: 73728
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerLongAlb
UserDataDict offset: 22208
UserDataDict count: 7
UserData offset: 22176
UserData count: 7
0
4096
5120
5632
6144
6656
7168
7680
SaveUserData: 22792, 7
SaveUserDataData: 23240, 45
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 0
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 6
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 32
Height: 32
Depth: 1
Array count: 12
Texture layout: 0
Texture layout2: 65543
Total size: 43008
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerNormalAlb
UserDataDict offset: 23968
UserDataDict count: 7
UserData offset: 23936
UserData count: 7
0
1024
1536
2048
2560
3072
SaveUserData: 24536, 7
SaveUserDataData: 24984, 60
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 0
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 6
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 32
Height: 32
Depth: 1
Array count: 18
Texture layout: 0
Texture layout2: 65543
Total size: 64512
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerPetalAlb
UserDataDict offset: 25848
UserDataDict count: 7
UserData offset: 25816
UserData count: 7
0
1024
1536
2048
2560
3072
SaveUserData: 26416, 7
SaveUserDataData: 26864, 90
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 3
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 9
Sample Count: 1
Surface format: BC1_SRGB
Access flags: Texture
Width: 256
Height: 256
Depth: 1
Array count: 6
Texture layout: 3
Texture layout2: 65543
Total size: 294912
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerStoneAlb
UserDataDict offset: 28016
UserDataDict count: 7
UserData offset: 27984
UserData count: 7
0
32768
40960
43008
43520
44032
44544
45056
45568
SaveUserData: 28608, 7
SaveUserDataData: 29056, 30
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 1
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 7
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 64
Height: 64
Depth: 1
Array count: 5
Texture layout: 1
Texture layout2: 65543
Total size: 40960
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerShellAlb
UserDataDict offset: 29632
UserDataDict count: 7
UserData offset: 29600
UserData count: 7
0
4096
5120
5632
6144
6656
7168
SaveUserData: 30208, 7
SaveUserDataData: 30656, 25
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 1
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 7
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 64
Height: 64
Depth: 1
Array count: 6
Texture layout: 1
Texture layout2: 65543
Total size: 49152
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: FlowerChipsAlb
UserDataDict offset: 31192
UserDataDict count: 7
UserData offset: 31160
UserData count: 7
0
4096
5120
5632
6144
6656
7168
SaveUserData: 31768, 7
SaveUserDataData: 32216, 30
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 3
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 3
Mip count: 9
Sample Count: 1
Surface format: BC4_UNORM
Access flags: Texture
Width: 256
Height: 256
Depth: 1
Array count: 1
Texture layout: 3
Texture layout2: 65543
Total size: 49152
Alignment: 512
Channels: 33686018
Surface dim: Dim2DArray
Name: GrassCoverAlb
UserDataDict offset: 32792
UserDataDict count: 7
UserData offset: 32760
UserData count: 7
0
32768
40960
43008
43520
44032
44544
45056
45568
SaveUserData: 33384, 7
SaveUserDataData: 33832, 5
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 1
Mip count: 9
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 256
Height: 128
Depth: 1
Array count: 2
Texture layout: 2
Texture layout2: 65543
Total size: 94208
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: GrassCrossAlb
UserDataDict offset: 34176
UserDataDict count: 7
UserData offset: 34144
UserData count: 7
0
32768
40960
43008
44032
44544
45056
45568
46080
SaveUserData: 34768, 7
SaveUserDataData: 35216, 10
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 4
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 11
Sample Count: 1
Surface format: BC1_SRGB
Access flags: Texture
Width: 1024
Height: 1024
Depth: 1
Array count: 83
Texture layout: 4
Texture layout2: 65543
Total size: 58474496
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: MaterialAlb
UserDataDict offset: 35600
UserDataDict count: 7
UserData offset: 35568
UserData count: 7
0
524288
655360
688128
696320
698368
698880
699392
699904
700416
700928
SaveUserData: 36208, 7
SaveUserDataData: 36656, 440
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 4
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 2
Mip count: 10
Sample Count: 1
Surface format: BC1_UNORM
Access flags: Texture
Width: 512
Height: 512
Depth: 1
Array count: 83
Texture layout: 4
Texture layout2: 65543
Total size: 14958592
Alignment: 512
Channels: 67371778
Surface dim: Dim2DArray
Name: MaterialCmb
UserDataDict offset: 41168
UserDataDict count: 7
UserData offset: 41136
UserData count: 7
0
131072
163840
172032
174080
174592
175104
175616
176128
176640
SaveUserData: 41768, 7
SaveUserDataData: 42216, 440
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 128
Height: 128
Depth: 1
Array count: 100
Texture layout: 2
Texture layout2: 65543
Total size: 2457600
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: Tree0Alb
UserDataDict offset: 46728
UserDataDict count: 7
UserData offset: 46696
UserData count: 7
0
16384
20480
21504
22016
22528
23040
23552
SaveUserData: 47312, 7
SaveUserDataData: 47760, 500
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC1_UNORM
Access flags: Texture
Width: 128
Height: 128
Depth: 1
Array count: 100
Texture layout: 2
Texture layout2: 65543
Total size: 1433600
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: Tree0NrmTrs
UserDataDict offset: 52848
UserDataDict count: 7
UserData offset: 52816
UserData count: 7
0
8192
10240
10752
11264
11776
12288
12800
SaveUserData: 53432, 7
SaveUserDataData: 53880, 500
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 0
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 6
Sample Count: 1
Surface format: BC4_UNORM
Access flags: Texture
Width: 32
Height: 32
Depth: 1
Array count: 1
Texture layout: 0
Texture layout2: 65543
Total size: 3072
Alignment: 512
Channels: 16908802
Surface dim: Dim2D
Name: TreeDitherMask
UserDataDict offset: 58968
UserDataDict count: 0
UserData offset: 58936
UserData count: 0
0
512
1024
1536
2048
2560
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC3_SRGB
Access flags: Texture
Width: 64
Height: 128
Depth: 1
Array count: 49
Texture layout: 2
Texture layout2: 65543
Total size: 702464
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: Tree1Alb
UserDataDict offset: 59688
UserDataDict count: 7
UserData offset: 59656
UserData count: 7
0
8192
10240
10752
11264
11776
12288
12800
SaveUserData: 60272, 7
SaveUserDataData: 60720, 245
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC1_UNORM
Access flags: Texture
Width: 64
Height: 128
Depth: 1
Array count: 49
Texture layout: 2
Texture layout2: 65543
Total size: 401408
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: Tree1NrmTrs
UserDataDict offset: 63368
UserDataDict count: 7
UserData offset: 63336
UserData count: 7
0
4096
5120
5632
6144
6656
7168
7680
SaveUserData: 63952, 7
SaveUserDataData: 64400, 245
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 0
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 1
Sample Count: 1
Surface format: D32_FLOAT_S8X24_UINT
Access flags: Texture
Width: 7
Height: 1
Depth: 1
Array count: 8
Texture layout: 0
Texture layout2: 65543
Total size: 4096
Alignment: 512
Channels: 84148994
Surface dim: Dim2DArray
Name: WaterAlb
UserDataDict offset: 67048
UserDataDict count: 7
UserData offset: 67016
UserData count: 7
0
SaveUserData: 67576, 7
SaveUserDataData: 68024, 40
Version major 2: 4, Version minor: 0
sparseResidency 0 sparseBinding 0 BlockHeightLog2 2
Flags: 1
Dims: Dim2D
Tile mode: Default
Swizzle: 0
Mip count: 8
Sample Count: 1
Surface format: BC4_UNORM
Access flags: Texture
Width: 32
Height: 128
Depth: 1
Array count: 2
Texture layout: 2
Texture layout2: 65543
Total size: 12288
Alignment: 512
Channels: 33686018
Surface dim: Dim2DArray
Name: GrassSpm
UserDataDict offset: 68696
UserDataDict count: 7
UserData offset: 68664
UserData count: 7
0
2048
3072
3584
4096
4608
5120
5632
SaveUserData: 69280, 7
SaveUserDataData: 69728, 10
Pos = 32 1 13 0 ResFile
Pos = 152 1 2 0 External Files
Pos = 176 1 1 0 String pool
Pos = 272 2 1 1 
Pos = 240 1 1 0 External files`

Notice how the mip offsets are written for each individual texture, not incrementally for the parent file.

Maybe KillzXGaming has an idea of how to fix this? Also the UserData section needs the Add and Remove functionality.
