### ISSUE TITLE
After update I can't save edits to BotW .pack

### ISSUE THREAD

**Issue by OrionKaelin** [KillzXGaming/Switch-Toolbox#458]
After updating to the latest version I can no longer edit and save files the way I was recently.

![screenshot 5](https://user-images.githubusercontent.com/34783733/154530978-98a35b90-a2d0-4c74-8d0c-9e621e12f7b4.jpg)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: buffer
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at LayoutBXLYT.Cafe.USD1.Write(FileWriter writer, LayoutHeader header) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\USD1.cs:line 75
   at LayoutBXLYT.Cafe.PartProperty.WriteUserData(FileWriter writer, LayoutHeader header, Int64 startPos) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Panes\PRT1.cs:line 398
   at LayoutBXLYT.Cafe.PRT1.Write(FileWriter writer, LayoutHeader header) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Panes\PRT1.cs:line 250
   at LayoutBXLYT.LayoutHeader.WriteSection(FileWriter writer, String magic, SectionCommon section, Action WriteMethod) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\Common.cs:line 1646
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 536
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 553
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 553
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 553
   at LayoutBXLYT.Cafe.Header.Write(FileWriter writer) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 512
   at Toolbox.Library.ArchiveFileInfo.SaveFileFormat()
   at Toolbox.Library.ArchiveFileWrapper.OnFormSaved(Object sender, EventArgs args)
   at LayoutBXLYT.LayoutEditor.SaveActiveFile(IFileFormat fileFormat, Boolean ForceDialog) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\GUI\BFLYT\LayoutEditor.cs:line 899
   at LayoutBXLYT.LayoutEditor.toolStripButton1_Click(Object sender, EventArgs e) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\GUI\BFLYT\LayoutEditor.cs:line 968
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///C:/Emulation/Toolbox-Latest/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/OpenTK.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Octokit.DLL
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Newtonsoft.Json.dll
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.BinaryData.dll
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/SPICA.DLL
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
SARCExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/SARCExt.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
DirectXTexNet
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Emulation/Toolbox-Latest/DirectXTexNet.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

![screenshot 6](https://user-images.githubusercontent.com/34783733/154531094-25d020a6-9aba-436d-a072-5fba6ea0e6b9.jpg)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: buffer
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at LayoutBXLYT.Cafe.USD1.Write(FileWriter writer, LayoutHeader header) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\USD1.cs:line 75
   at LayoutBXLYT.Cafe.PartProperty.WriteUserData(FileWriter writer, LayoutHeader header, Int64 startPos) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Panes\PRT1.cs:line 398
   at LayoutBXLYT.Cafe.PRT1.Write(FileWriter writer, LayoutHeader header) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Panes\PRT1.cs:line 250
   at LayoutBXLYT.LayoutHeader.WriteSection(FileWriter writer, String magic, SectionCommon section, Action WriteMethod) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\Common.cs:line 1646
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 536
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 553
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 553
   at LayoutBXLYT.Cafe.Header.WritePanes(FileWriter writer, BasePane pane, LayoutHeader header, Int32& sectionCount) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 553
   at LayoutBXLYT.Cafe.Header.Write(FileWriter writer) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Layout\CAFE\Header.cs:line 512
   at Toolbox.Library.ArchiveFileInfo.SaveFileFormat()
   at FirstPlugin.SARC.Save(Stream stream) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Archives\SARC.cs:line 257
   at Toolbox.Library.ArchiveFileInfo.SaveFileFormat()
   at FirstPlugin.SARC.Save(Stream stream) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Archives\SARC.cs:line 257
   at Toolbox.Library.IO.STFileSaver.SaveFileFormat(IFileFormat FileFormat, String FileName, Boolean EnableDialog, String DetailsLog)
   at Toolbox.MainForm.SaveNodeFormats(ObjectEditor editor, Boolean UseSaveDialog, Boolean UseCompressDialog) in C:\projects\switch-toolbox-fkj3m\Toolbox\MainForm.cs:line 503
   at Toolbox.MainForm.SaveActiveFile(Boolean UseSaveDialog, Boolean UseCompressDialog) in C:\projects\switch-toolbox-fkj3m\Toolbox\MainForm.cs:line 389
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///C:/Emulation/Toolbox-Latest/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/OpenTK.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Octokit.DLL
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Newtonsoft.Json.dll
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Syroot.BinaryData.dll
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/SPICA.DLL
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
SARCExt
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/SARCExt.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Emulation/Toolbox-Latest/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
DirectXTexNet
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Emulation/Toolbox-Latest/DirectXTexNet.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by NateHevens** [comment]
I've been having this issue, as well!
