### ISSUE TITLE
Switch Sports specific animation files

### ISSUE THREAD

**Issue by NewSkyLineTwitter** [KillzXGaming/Switch-Toolbox#487]
There a few animation .bfres.zs files that STB can't load. It gives me this error: 

```
System.ArgumentNullException: Der Puffer darf nicht NULL sein.
Parametername: buffer
   bei System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   bei FirstPlugin.BFRES.LoadFile(ResFile res) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\BFRES.cs:Zeile 1298.
   bei FirstPlugin.BFRES.Load(Stream stream) in C:\projects\switch-toolbox\File_Format_Library\FileFormats\BFRES\BFRES.cs:Zeile 814.
   bei Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
   bei Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   bei Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   bei Toolbox.Library.ExplorerFile.OpenFile()
   bei Toolbox.Library.ExplorerFile.OnDoubleMouseClick(TreeView treeview)
   bei Toolbox.Library.Forms.ObjectEditorTree.treeViewCustom1_DoubleClick(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Any help would be nice 😊

If needed the file:
[AnimationFile.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/8862952/AnimationFile.zip)

**Comment by CoocooFroggy** [comment]
I am having the same issue. Decompression works fine but loading the bfres fails.

```
System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at FirstPlugin.BFRES.LoadFile(ResFile res) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\BFRES\BFRES.cs:line 1298
   at FirstPlugin.BFRES.Load(Stream stream) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\BFRES\BFRES.cs:line 814
   at Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.ExplorerFile.OpenFile()
   at Toolbox.Library.ExplorerFile.OnDoubleMouseClick(TreeView treeview)
   at Toolbox.Library.Forms.ObjectEditorTree.treeViewCustom1_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by CoocooFroggy** [comment]
Was this fixed?
