### ISSUE TITLE
Unhandled exception when opening a "bars.zs" file

### ISSUE THREAD

**Issue by CalebKOnline** [KillzXGaming/Switch-Toolbox#507]
So I'm trying to do some datamining for myself and when trying to open sound effects I get this
![image](https://user-images.githubusercontent.com/85580091/187097911-d7a4c94c-0695-42aa-a27d-559e25e188e1.png)

Full error:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Invalid signature, expected 'DATA' but got 'AMTA'.
   at BarsLib.IO.FileLoader.CheckSignature(String validSignature)
   at BarsLib.AMTADATA.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.IO.FileLoader.ReadResData[T]()
   at BarsLib.IO.FileLoader.Load[T](Boolean SeekOffset, UInt32 offset)
   at BarsLib.AMTA.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.IO.FileLoader.ReadResData[T]()
   at BarsLib.IO.FileLoader.Load[T](Boolean SeekOffset, UInt32 offset)
   at BarsLib.BARS.BarsLib.IO.IFileData.Load(FileLoader loader)
   at BarsLib.BARS..ctor(Stream stream)
   at FirstPlugin.BARS.Load(Stream stream) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\Audio\BARS\BARS.cs:line 240
   at Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.ExplorerFile.OpenFile()
   at Toolbox.Library.ExplorerFile.OnDoubleMouseClick(TreeView treeview)
   at Toolbox.Library.Forms.ObjectEditorTree.treeViewCustom1_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.141.0
    Win32 Version: 1.0.141
    CodeBase: file:///D:/Switch%20Toolbox/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.141.0
    Win32 Version: 1.0.141
    CodeBase: file:///D:/Switch%20Toolbox/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///D:/Switch%20Toolbox/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/Switch%20Toolbox/Lib/OpenTK.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///D:/Switch%20Toolbox/Octokit.DLL
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///D:/Switch%20Toolbox/Lib/SFGraphics.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/Switch%20Toolbox/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.141.0
    Win32 Version: 1.0.141
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Switch%20Toolbox/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Newtonsoft.Json.dll
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Syroot.BinaryData.dll
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Plugins/SPICA.DLL
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ZstdNet
    Assembly Version: 1.3.3.0
    Win32 Version: 1.3.3.0
    CodeBase: file:///D:/Switch%20Toolbox/ZstdNet.DLL
----------------------------------------
BarsLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Switch%20Toolbox/Lib/BarsLibrary.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by KillzXGaming** [comment]
Newer .bars format are not supported (introduced around ACNH). Not sure if I plan to support these for awhile, my .bars library really needs a rewrite since it is quite a mess. Also if anyone has documented the changes or has working tools, a link to those would be useful.

**Comment by Hedwig7s** [comment]
> Newer .bars format are not supported (introduced around ACNH). Not sure if I plan to support these for awhile, my .bars library really needs a rewrite since it is quite a mess. Also if anyone has documented the changes or has working tools, a link to those would be useful.

https://wiki.oatmealdome.me/Aal/BARS_(File_Format)
Could this be of any help?

**Comment by whamer100** [comment]
> > Newer .bars format are not supported (introduced around ACNH). Not sure if I plan to support these for awhile, my .bars library really needs a rewrite since it is quite a mess. Also if anyone has documented the changes or has working tools, a link to those would be useful.
> 
> https://wiki.oatmealdome.me/Aal/BARS_(File_Format) Could this be of any help?

this is for the BARS format itself, the issue is related to the newer AMTA metadata entries (specifically being for v5). I've implemented a parser in C++ on my github, but it's kind-of a mess, and it doesnt support adding new entries (it also currently strictly works only on v5 AMTA entries)

I'm sure the avsys wiki has plenty of info on it, if only we could actually access it :/

**Comment by MonsterDruide1** [comment]
> I'm sure the avsys wiki has plenty of info on it, if only we could actually access it :/

After I've requested access to their wiki, they just put all sites on the Switch documentation to public.

**Comment by whamer100** [comment]
> > I'm sure the avsys wiki has plenty of info on it, if only we could actually access it :/
> 
> After I've requested access to their wiki, they just put all sites on the Switch documentation to public.

oh wait really? I requested access a while back and everything was still privated, thanks for the heads up!
