### ISSUE TITLE
Can't import Doc Louis's Punch-Out model files

### ISSUE THREAD

**Issue by Roboguy420** [KillzXGaming/Switch-Toolbox#518]
The model files for the main title, Punch-Out Wii, all import perfectly fine, but when I try importing the files for the WiiWare title Doc Louis's Punch-Out, I get an unhandled exception error with the message "Non-negative number required. Parameter name: count."

It also spits this out in the details which might be important:

> System.ArgumentOutOfRangeException: Non-negative number required.
> Parameter name: count
>    at System.IO.BinaryReader.ReadBytes(Int32 count)
>    at FirstPlugin.PunchOutWii.PO_DICT.Load(Stream stream) in C:\projects\switch-toolbox-fkj3m\File_Format_Library\FileFormats\NLG\PunchOutWii\PO_DICT.cs:line 70
>    at Toolbox.Library.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat FileCompression)
>    at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
>    at Toolbox.Library.IO.STFileLoader.OpenFileFormat(String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, UInt32 DecompressedSize, UInt32 CompressedSize)
>    at Toolbox.MainForm.OpenFile(String FileName, Boolean InActiveEditor) in C:\projects\switch-toolbox-fkj3m\Toolbox\MainForm.cs:line 279
>    at Toolbox.MainForm.OpenFileSelect() in C:\projects\switch-toolbox-fkj3m\Toolbox\MainForm.cs:line 250
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I'm guessing there's some weird difference between how the files work in the WiiWare title compared to the main game, which is why this error occurs. If there's any fix for this, or if there's some other way to extract the model files, please let me know. Thanks

**Comment by KillzXGaming** [comment]
Need sample files.

**Comment by Roboguy420** [comment]
[doc louis punchout files.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/9692040/doc.louis.punchout.files.zip)
