### ISSUE TITLE
How do I view zs file in tears of the kingdom

### ISSUE THREAD

**Issue by zrzrv5** [KillzXGaming/Switch-Toolbox#591]
Hi, i want to view some byml.zs file, but the toolbox cannot decompress it.

ZstdNet.ZstdException: Dictionary mismatch
   at ZstdNet.ReturnValueExtensions.ThrowException(UIntPtr returnValue, String message)
   at ZstdNet.ReturnValueExtensions.EnsureZstdSuccess(UIntPtr returnValue)
   at ZstdNet.Decompressor.Unwrap(ArraySegment`1 src, Byte[] dst, Int32 offset, Boolean bufferSizePrecheck)
   at ZstdNet.Decompressor.Unwrap(ArraySegment`1 src, Int32 maxDecompressedSize)
   at ZstdNet.Decompressor.Unwrap(Byte[] src, Int32 maxDecompressedSize)
   at Toolbox.Library.Zstb.SDecompress(Byte[] b)
   at Toolbox.Library.Zstb.Decompress(Stream stream)
   at Toolbox.Library.IO.CompressionMenus.SaveFileForCompression(Boolean Compress, String[] fileNames, ICompressionFormat compressionFormat)

**Comment by mdtauk** [comment]
I think there was some kind of buffer size issue from what I understand.  It must be some new form of Zstandard compression right?

**Comment by zoeysaurusrex** [comment]
For the ones that won't open, you need to grab the *.dic files from the Pack folder, then use zstd from console with those dictionary files to unpack them

**Comment by mdtauk** [comment]
> 

How would you do that with Font/Font.Nin_NX_NVN.bfarc.zs

**Comment by kxs-exe** [comment]
> For the ones that won't open, you need to open ZsDic.zs from the Pack folder, then use the *.dic files with zstd from console to unpack them

I was able to unpack stuff externally with zstd, thanks to this. But i have abolutely no Idea how to make zstd in Toolbox use these dictionarys. Any reccomendations?

**Comment by blanc-cake** [comment]
For anyone needing a step-by-step guide -

1. Download an unzip the latest zstd release from the [ZStandard releases](https://github.com/facebook/zstd/releases/latest/) page.
2. Using either `zstd.exe` or Switch Toolbox, decompress `Pack/ZsDic.pack.zs` to get `ZsDic.pack`:
**With zstd -**
`zstd --decompress ZsDic.pack.zs -o ZsDic.pack`
**With Switch Toolbox -**
`Tools > Compression > ZSTD > Decompress`, pick `ZsDic.pack.zs` and save as `ZsDic.pack`.
3. Open `ZsDic.pack` in Switch-Toolbox, and extract the 3 `*.zsdic` dictionary files inside.

Using these dictionaries with `zstd.exe` (requires the `-D` parameter) will allow you to decompress different ZS files for use with Switch Toolbox.
For example:
- `zstd --decompress Font.Nin_NX_NVN.bfarc.zs -D zs.zsdic -o Font.Nin_NX_NVN.bfarc`
- `zstd --decompress Bootup.Nin_NX_NVN.pack.zs -D pack.zsdic -o Bootup.Nin_NX_NVN.pack`
- `zstd --decompress Dungeon151_Static.bcett.byml.zs -D bcett.byml.zsdic -o Dungeon151_Static.bcett.byml`

**Comment by mdtauk** [comment]
> * zstd --decompress Font.Nin_NX_NVN.bfarc.zs -D zs.zsdic -o Font.Nin_NX_NVN.bfarc

Thank you for posting this.  Hopefully Switch Toolbox can add support for Zstd with custom dictionary in the future :D

**Comment by azridere** [comment]
How would I properly re-compress the file for use in ToTK?

**Comment by ArchLeaders** [comment]
You can use https://github.com/TotkMods/Totk.ZstdTool for compression and decompression

**Comment by simm4256** [comment]
where is ZsDic.pack.zs file? I cant find that

**Comment by ObscenityIB** [comment]
None of these tools can unpack the `ZsDic.pack.zs` files.

**Toolbox**
```
ZstdNet.ZstdException: Can't create buffer for data with unspecified decompressed size (provide your own buffer to Unwrap instead)
   at ZstdNet.Decompressor.Unwrap(ArraySegment`1 src, Int32 maxDecompressedSize)
   at ZstdNet.Decompressor.Unwrap(Byte[] src, Int32 maxDecompressedSize)
   at Toolbox.Library.Zstb.SDecompress(Byte[] b)
   at Toolbox.Library.Zstb.Decompress(Stream stream)
   at Toolbox.Library.IO.CompressionMenus.SaveFileForCompression(Boolean Compress, String[] fileNames, ICompressionFormat compressionFormat)
```

**ZSTD Tool**
```
System.TypeInitializationException: The type initializer for 'Totk.ZStdTool.Helpers.ZStdHelper' threw an exception.
 ---> ZstdSharp.ZstdException: Decompressed content size cannot be determined (e.g. invalid magic number, srcSize too small)
   at ZstdSharp.ThrowHelper.EnsureContentSizeOk(UInt64 returnValue)
   at ZstdSharp.Decompressor.GetDecompressedSize(ReadOnlySpan`1 src)
   at ZstdSharp.Decompressor.Unwrap(ReadOnlySpan`1 src, Int32 maxDecompressedSize)
   at Totk.ZStdTool.Helpers.ZStdHelper..cctor() in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\Helpers\ZStdHelper.cs:line 17
   --- End of inner exception stack trace ---
   at Totk.ZStdTool.Helpers.ZStdHelper.Decompress(String file) in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\Helpers\ZStdHelper.cs:line 31
   at Totk.ZStdTool.ViewModels.ShellViewModel.Decompress() in D:\a\Totk.ZStdTool\Totk.ZStdTool\src\ViewModels\ShellViewModel.cs:line 80
```

**zstd**
```
zstd: C:\Users\Obscenity\Downloads\NUT\x\tools\pack\ZsDic.pack.zs: unsupported format
```

Kinda stuck here now.

>Name: ZsDic.pack.zs
>Size: 108344 bytes (105 KiB)
>SHA256: 4fd553186b6ada4fa3a7befd3a2198f5464e1f0fdd9c519b08d9cfd1c33297a7
>SHA1: 186a8c3c8e522cbb5a4aa30e3a20a5400ec4b010

**Comment by ICE209** [comment]
He taught very well, thanks very much. I have succeeded

**Comment by yussufussi92-lab** [comment]
Pubg
