### ISSUE TITLE
"Dictionary mismatch" Tears of the Kingdom .zs compressed files

### ISSUE THREAD

**Issue by guighub** [KillzXGaming/Switch-Toolbox#599]
I've just dumped my copy of TOTK and am trying to load some of the models, it looks like the .zs format was updated or something because I get the following error:
![image](https://github.com/KillzXGaming/Switch-Toolbox/assets/74810584/e6c0f7c8-5009-4f85-977c-ed1c82f0497c)

**Comment by Pysis868** [comment]
https://github.com/KillzXGaming/Switch-Toolbox/issues/591#issuecomment-1535947535

**Comment by tlf30** [comment]
I am using version 1.0.211, and hitting the same issue.
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
ZstdNet.ZstdException: Dictionary mismatch
   at ZstdNet.ReturnValueExtensions.ThrowException(UIntPtr returnValue, String message)
   at ZstdNet.ReturnValueExtensions.EnsureZstdSuccess(UIntPtr returnValue)
   at ZstdNet.Decompressor.Unwrap(ArraySegment`1 src, Byte[] dst, Int32 offset, Boolean bufferSizePrecheck)
   at ZstdNet.Decompressor.Unwrap(ArraySegment`1 src, Int32 maxDecompressedSize)
   at ZstdNet.Decompressor.Unwrap(Byte[] src, Int32 maxDecompressedSize)
   at Toolbox.Library.Zstb.SDecompress(Byte[] b)
   at Toolbox.Library.Zstb.Decompress(Stream stream)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, Int64 DecompressedSize, Int64 CompressedSize)
   at Toolbox.Library.IO.STFileLoader.OpenFileFormat(String FileName, Boolean LeaveStreamOpen, Boolean InArchive, Boolean Compressed, ICompressionFormat CompressionFormat, UInt32 DecompressedSize, UInt32 CompressedSize)
   at Toolbox.MainForm.OpenFile(String FileName, Boolean InActiveEditor) in C:\projects\switch-toolbox-fkj3m\Toolbox\MainForm.cs:line 279
   at Toolbox.MainForm.OpenFileSelect() in C:\projects\switch-toolbox-fkj3m\Toolbox\MainForm.cs:line 250
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Toolbox
    Assembly Version: 1.0.211.0
    Win32 Version: 1.0.211
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Toolbox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Toolbox.Library
    Assembly Version: 1.0.211.0
    Win32 Version: 1.0.211
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Toolbox.Library.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DirectXTexNetImpl
    Assembly Version: 1.0.0.3
    Win32 Version: 
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/x64/DirectXTexNetImpl.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/OpenTK.dll
----------------------------------------
SFGraphics
    Assembly Version: 1.0.6956.42501
    Win32 Version: 1.0.6956.42501
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/SFGraphics.dll
----------------------------------------
Octokit
    Assembly Version: 0.31.0.0
    Win32 Version: 0.31.0.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Octokit.DLL
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/OpenTK.GLControl.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
FirstPlugin.Plg
    Assembly Version: 1.0.211.0
    Win32 Version: 1.0.211
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Plugins/FirstPlugin.Plg.dll
----------------------------------------
GL_EditorFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/GL_EditorFramework.DLL
----------------------------------------
FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Plugins/FlatBuffers.DLL
----------------------------------------
Syroot.NintenTools.NSW.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bfres.dll
----------------------------------------
Syroot.Maths
    Assembly Version: 1.5.3.0
    Win32 Version: 1.5.3.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Syroot.Maths.DLL
----------------------------------------
Syroot.NintenTools.Bfres
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Syroot.NintenTools.Bfres.dll
----------------------------------------
Syroot.BinaryData
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Syroot.BinaryData.dll
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Plugins/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Newtonsoft.Json.dll
----------------------------------------
Syroot.NintenTools.NSW.Bntx
    Assembly Version: 1.2.3.0
    Win32 Version: 1.2.3.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Syroot.NintenTools.NSW.Bntx.dll
----------------------------------------
SPICA
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Plugins/SPICA.DLL
----------------------------------------
ZeldaLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/Lib/Plugins/ZeldaLib.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ZstdNet
    Assembly Version: 1.3.3.0
    Win32 Version: 1.3.3.0
    CodeBase: file:///D:/ryujinx-1.1.800-win_x64/modding/Toolbox-Latest/ZstdNet.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by tlf30** [comment]
Ah OK, follow the solution here and it works: https://github.com/KillzXGaming/Switch-Toolbox/issues/591#issuecomment-1546988309
