### ISSUE TITLE
TOTK BFRES cannot export

### ISSUE THREAD

**Issue by CharlesRBLX** [KillzXGaming/Switch-Toolbox#626]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.LoadString(Encoding encoding)
   at Syroot.NintenTools.NSW.Bfres.ResDict.ReadNode(ResFileLoader loader)
   at Syroot.NintenTools.NSW.Bfres.ResDict.Syroot.NintenTools.NSW.Bfres.Core.IResData.Load(ResFileLoader loader)
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.LoadDict()
   at Syroot.NintenTools.NSW.Bfres.MaterialParserV10.ShaderAssignV10.Syroot.NintenTools.NSW.Bfres.Core.IResData.Load(ResFileLoader loader)
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.ReadResData[T]()
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.Load[T](Boolean Relocated)
   at Syroot.NintenTools.NSW.Bfres.MaterialParserV10.ShaderInfo.Syroot.NintenTools.NSW.Bfres.Core.IResData.Load(ResFileLoader loader)
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.ReadResData[T]()
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.Load[T](Boolean Relocated)
   at Syroot.NintenTools.NSW.Bfres.MaterialParserV10.Load(ResFileLoader loader, Material mat)
   at Syroot.NintenTools.NSW.Bfres.Material.Syroot.NintenTools.NSW.Bfres.Core.IResData.Load(ResFileLoader loader)
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.ReadResData[T]()
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.LoadList[T](Int32 count, Nullable`1 offset)
   at Syroot.NintenTools.NSW.Bfres.Model.Syroot.NintenTools.NSW.Bfres.Core.IResData.Load(ResFileLoader loader)
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.ReadResData[T]()
   at Syroot.NintenTools.NSW.Bfres.Core.ResFileLoader.LoadList[T](Int32 count, Nullable`1 offset)

exact error right here ^
                                    |

i was trying to export what i thought was the gloom spawn (the hands)

but then i get this error even though its a bfres any way how to fix it?

**Comment by CharlesRBLX** [comment]
NVM, i was on an older version
